//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string SID { get; set; }
        public byte Term_ID { get; set; }
        public System.DateTime Date_Time { get; set; }
        public bool Attendance1 { get; set; }
        public Nullable<bool> Allowed { get; set; }
    
        public virtual Term Term { get; set; }
        public virtual Student Student { get; set; }
    }
}
