//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    
    public partial class class_info_Result1
    {
        public string Number { get; set; }
        public string day { get; set; }
        public string hour { get; set; }
        public string EID { get; set; }
        public string Instr_Name { get; set; }
        public string SID { get; set; }
    }
}
