//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public string Number { get; set; }
        public string day { get; set; }
        public string hour { get; set; }
        public string EID { get; set; }
        public string Instr_Name { get; set; }
        public string SID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher_Instr Teacher_Instr { get; set; }
    }
}
