//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Term
    {
        public byte Term_Num { get; set; }
        public byte Term_ID { get; set; }
        public string Pay_ID { get; set; }
        public string SID { get; set; }
        public System.DateTime Register_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Student Student { get; set; }
        public virtual Term Term { get; set; }
    }
}
