//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Term()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Student_Term = new HashSet<Student_Term>();
        }
    
        public byte Term_ID { get; set; }
        public string EID { get; set; }
        public string Instr_Name { get; set; }
        public Nullable<byte> Session_Count { get; set; }
        public Nullable<int> Session_Price { get; set; }
        public Nullable<byte> Session_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Term> Student_Term { get; set; }
        public virtual Teacher_Instr Teacher_Instr { get; set; }
    }
}
